#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR" || exit

OLLAMA_CONTEXT_LENGTH="${OLLAMA_CONTEXT_LENGTH:-8192}"
OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:-30m}"
OLLAMA_NUM_PARALLEL="${OLLAMA_NUM_PARALLEL:-1}"
OLLAMA_MAX_LOADED_MODELS="${OLLAMA_MAX_LOADED_MODELS:-1}"
OLLAMA_FLASH_ATTENTION="${OLLAMA_FLASH_ATTENTION:-true}"

echo "Starting Ollama with tuned defaults:"
echo "  OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH}"
echo "  OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE}"
echo "  OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL}"
echo "  OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS}"
echo "  OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION}"

exec env \
  OLLAMA_CONTEXT_LENGTH="${OLLAMA_CONTEXT_LENGTH}" \
  OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE}" \
  OLLAMA_NUM_PARALLEL="${OLLAMA_NUM_PARALLEL}" \
  OLLAMA_MAX_LOADED_MODELS="${OLLAMA_MAX_LOADED_MODELS}" \
  OLLAMA_FLASH_ATTENTION="${OLLAMA_FLASH_ATTENTION}" \
  ollama serve
